# Welcome to Lab: Similarity 🧍🧍‍♂️🧍‍♀️

Many of you already know your group members in this class. However, have you ever wondered if there is someone **even more similar** to you than the people you already know?

In this lab, we'll once again explore the dataset from the **Hello Survey** you've completed, utilizing some new Python skills to calculate your similarity to your peers!

A few tips to remember:

- **You are not alone on your journey in learning programming!**  You have your lab TA, your CAs, your lab group, and the professors (Prof. Wade and Prof. Karle), who are all here to help you out!
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

In [105]:
# Meet your CAs and TA if you haven't already!
# ...first name is enough, we'll know who they are! :)
ta_name = "Jake"
ca1_name = "Sophie"
ca2_name = "Maddy"
ca3_name = ""


# Say hello to each other!
# - Groups of 3 are ideal :)
# - However, groups of 2 or 4 are fine too!

# QOTD to ask your group: What's your favorite (or least favorite) building on campus? 
partner1_name = "Esther"
partner1_netid = ""
partner1_favbuilding = "Siebel Center of Design "

partner2_name = "Savanah"
partner2_netid = ""
partner2_favbuilding = "Dunkin"

partner3_name = ""
partner3_netid = ""
partner3_favbuilding = ""

# Which lab section are you in? Record it below! It should start with a Y and have 
# 2 numbers after the Y. If you're unsure - ask your TA/CAs!
lab_section = "Y01"

<hr style="color: #DD3403;">

# Part 1: Hello, Again

## Load the Hello Dataset
To find the people most similar to you in this course, we're going to need the Hello Dataset again.


The "Hello Dataset" is available here:
```
https://waf.cs.illinois.edu/discovery/hello-fa25.csv
```

Use Python to load this dataset into a DataFrame `df`:

In [106]:
import pandas as pd
df= pd.read_csv("https://waf.cs.illinois.edu/discovery/hello-fa25.csv")
df

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
0,Prof. Wade,AL1,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Sweeden,Purple,Nerding Out,Pop EDM,Eagle,Physics,Taylor Swift,YouTube,Factorio,Mountain Cabin
1,Prof. Karle,AL1,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Maldives,pink,with people!!!,pop,sloth,computer science,Taylor Swift,instagram,cards,Maldives
2,Muhammad,Y20,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Malaysia,Green,Sleeping,Hip hop,Husky,Electrical Engineering,Kanye West,Instagram,Minecraft,Switzerland
3,Jake,Y10,Heads,Chocolate,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Norway,Yellow,Hang Out With Friends,Indie Music,Llama,Electrical Engineering,Tame Impala,Instagram,Volleyball,Switzerland Alps
4,Shourya,Y04,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,UAE,Red,Youtube,Indie pop,Wolf,Astrophysics,Cigarettes after sex,Instagram,Spy,Iceland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,arnav,Y31,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,Movies,...,Singapore,Blue,Hang out with friends,R&b,Lion,Chemical engineering,NaN,Instagram,NaN,Indonesia
1196,Lorenzo,Y11,Heads,Chocolate,Morning,Even,Yes,Summer,In Gies College of Business,Movies,...,Canada,blue,sleep,jazz,dog,cs,MBY,wechat,MC,Canada
1197,CA Emma,Y20,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Sweden,Green,Crocheting,Pop,Frog,Computer Science,Lady Gaga,TikTok,Minecraft,Italy
1198,CA Soph,Y01 Y14 Y15 Y18,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Mexico,Red,Relaxing,Hyperpop,Rabbit,Aerospace Engineering,Ayesha Erotica,Pinterest,Twister,Mexico City
1199,Jay,Y07,Tails,Vanilla,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Paris,Blue,On Tiktok,R&B,Wolf,Chem E,Mac Demarco,TikTok,Basketball,Hawaii

### 🔬 Test Case Checkpoint 🔬

In [107]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert("df" in vars()), "This is not the Hello Dataset you're looking for. Check the URL."
assert("Where is your dream vacation spot?" in df), "This is not the Hello Dataset you're looking for. Check the URL."
assert(len(df) >= 1140), "This is not the Hello Dataset you're looking for. Check the URL."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Finding Yourself
Before finding people you are **similar to**, you have to find **yourself** - literally!

### Puzzle 1.1: Your Row
In the following cell, write the Python code to create a **new** DataFrame with only yourself, named `df_me`, and then display it.

*Note: if you cannot find yourself in the Hello Dataset, try adding a space after your name within the string. If you did not fill out the Hello Survey, pick one of your TAs, CAs, or Professor Karle or Wade! Their names are in the survey in the format of "TA Alex" or "Prof. Karle".*

In [108]:
df_me= df[(df["Name"] == "Michelle") & (df["Lab"] == "Y01")]
df_me

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
798,Michelle,Y01,Heads,Vanilla,Night,Odd,Yes,Summer,Not in Gies,Movies,...,Spain,pink,Baking,Alternative Indie,cat,engineering,Black Party,tiktok,Sims,Grecce

### 🔬 Test Case Checkpoint 🔬

In [109]:
## == PUZZLE 1.1 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert("df_me" in vars()), "Make sure you named the DataFrame with just you `df_me`."
assert("Where is your dream vacation spot?" in df_me), "Your `df_me` should have the same columns as our `df`."
assert(len(df_me.columns.to_list()) == 160), "Your `df_me` should have the same number of columns as our original `df`."
assert(len(df_me) == 1), "Your `df_me` should only have one row: yourself."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## DataFrame vs. Series

In `pandas`, we have worked with **DataFrames** all semester long! DataFrames are similar to excel sheets and have rows and columns with data!

Another data type is called a **Series**.

- A **Series** is a single row with zero or more values (columns). You can think of a DataFrame as a collection of **Series** objects. When we deal with a single row, we will usually want to deal with a **Series** instead of a **one row DataFrame**

In this lab, we will learn how to convert from a **one row DataFrame** to a **Series**, but here's a quick rundown on how to convert from types:

### Converting Types

The `pandas` library makes it easy to convert between a **Series** and a **DataFrame**.

- From a **Series** (`row`) to a **DataFrame**:
    - `row.to_frame()`
- From a **DataFrame** (`df`) to a **Series**:
    - `df.iloc[0]`, if the DataFrame has one row

See this guide, https://discovery.cs.illinois.edu/guides/DataFrame-Fundamentals/dataframe-loc-vs-iloc/, for more information about `iloc[]`.

### Puzzle 1.2: Transform your row into a Series
Using the correct function from above, **transform** the `df_me` row containing only you from a **one-row DataFrame** into a **Series**. 

Make sure the Series is named `my_row` (this will match up with code we provide you with later):

In [110]:
my_row= df_me.iloc[0]
my_row

Name                                                                 Michelle
Lab                                                                       Y01
When flipping a coin, heads or tails?                                   Heads
Is your favorite ice cream flavor chocolate or vanilla?               Vanilla
Do you like morning or night?                                           Night
                                                                     ...
What do you think is the hardest major at UIUC?                   engineering
Who is your favorite music artist?                                Black Party
What's your favorite social media app?                                 tiktok
What is your favorite game to play (either video game or IRL)?           Sims
Where is your dream vacation spot?                                     Grecce
Name: 798, Length: 160, dtype: object

### 🔬 Test Case Checkpoint 🔬

In [111]:
## == PUZZLE 1.2 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('my_row' in vars()), "Your series should be named `my_row`."
assert(type(my_row) == pd.core.series.Series), "Make sure you've correctly converted your one-row DataFrame into a Series..."
assert(my_row.to_frame().T.equals(pd.DataFrame(df_me, dtype = 'O'))), "Make sure my_row corresponds to your row in df"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Choosing Your Columns

Before we begin, we have to think about our approach to finding your DISCOVERY twin.

You may have noticed our Hello Dataset has **more than 100 questions**. Instead of finding the most similar person to you using **every question**, we'll pick out a few questions to analyze that we think will do the best job at finding your twin! 

**But first, we need to revisit the questions.**

Recall the function `df.columns.tolist()`. To recap, this command will list **all of the columns** (in this case, our questions) in a DataFrame.

Use `df.columns.tolist()` in the cell below. 

<br>

**Viewing the Full Output**: When you do that, you will likely see the message:

> Output exceeds the __size limit__. Open the full output data __in a text editor__.

If you do, click the **in a text editor** link to open the whole list in a new tab of VSCode.

In [112]:
df.columns.tolist()

['Name',
 'Lab',
 'When flipping a coin, heads or tails?',
 'Is your favorite ice cream flavor chocolate or vanilla?',
 'Do you like morning or night?',
 'Is your favorite number even or odd?',
 'Do you have a pet?',
 'Do you prefer summer or winter?',
 'Are you in the Gies College of Business?',
 'Do you prefer Movies or TV shows?',
 'Do you prefer pizza or hamburgers?',
 'You describe yourself as:',
 'Do you prefer sweet or salty food?',
 'Do you eat breakfast?',
 'Do you speak a second language?',
 'Do you prefer cats or dogs?',
 'Do you prefer Italian or Mexican food?',
 'Cookies or Brownies?',
 'Do you like apples or bananas?',
 'Waffles or pancakes?',
 'Night Owl or Early Bird?',
 'Did you do high school in Illinois?',
 'Do you typically shower in the morning or at night?',
 'Do you prefer sweet or savory food?',
 'What month is your birthday?',
 'Do you use a Mac or Windows Laptop?',
 'Do you like pizza or pasta?',
 'Do you wear glasses?',
 'Fall or spring season?',
 'Do you prefer pink or blue?',
 'Does your UIN end with an even or odd number?',
 'Do you use corrective lenses (contacts/glasses)?',
 'Do you prefer Apple Music or Spotify?',
 'Do you have any siblings?',
 'Are you from Chicago?',
 'Pick a number: One or Two.',
 'Do you prefer basketball or football?',
 'Do you prefer the beach or mountains?',
 'Do you prefer breakfast or dinner?',
 'Do you prefer Coca Cola or Pepsi?',
 'Do you prefer coffee or tea?',
 'Are you an extrovert or introvert?',
 'Do you prefer hotdogs or hamburgers?',
 'Do you like Messi or Ronaldo?',
 'Have you ever been outside of United States?',
 'Do you have more than 1 sibling?',
 'Does pineapple belong on pizza?',
 'Do you live in Urbana or Champaign?',
 'Do you prefer sunny or rainy days?',
 'Red or Blue?',
 'Is your DISCOVERY lab the last class of your day?',
 'Have you had your 19th birthday?',
 'Are you a Statistics Major?',
 'Are you currently wearing shorts?',
 'Are you from Chicago or the suburbs?',
 'Are you registered for the 9am or 11am lecture?',
 'Are you team Edward or team Jacob?',
 'Cold Coffee or Hot Coffee?',
 'Did you go to the football game against WIU?',
 'Cookies or Ice Cream?',
 'Do you prefer urban or rural areas?',
 'Do you prefer creamy or chunky peanut butter?',
 'Dunkin or Starbucks?',
 'Football or soccer?',
 'Fruits or vegetables?',
 'Do you prefer gold or silver jewelry?',
 'Do you prefer hot or cold weather?',
 'Do you prefer in person or online classes?',
 'Do you prefer Instagram Reels or TikTok?',
 'Do you prefer Kendrick Lamar or Drake?',
 'Do you prefer ketchup or honey mustard?',
 'Do you prefer Lebron James or Michael Jordan?',
 'Do you eat beef?',
 'Do you exercise regularly?',
 'Do you game on a PC or Console?',
 'Do you have a brother?',
 'Do you prefer being hot or cold?',
 'Do you like chocolate ice cream?',
 'Do you like cilantro or not?',
 'Do you prefer DC or Marvel?',
 'Do you like ice cream?',
 'Do you like Mint Chocolate Chip ice cream?',
 'Do you like pizza?',
 'Red or Green?',
 'Do you like running?',
 'Do you like school?',
 'Sweet food or spicy food?',
 'Do you live in a dorm or apartment?',
 'Do you live in University Housing or Private Housing?',
 'Do you prefer Xbox or Playstation?',
 'Do you prefer travelling by plane or cruise?',
 'Breakfast or Lunch?',
 'Do you prefer lunch or dinner?',
 'Do you prefer mild or spicy food?',
 'Nike or Adidas?',
 'Do you prefer pens or pencils?',
 'Purple or orange?',
 'Red or Black?',
 'Sausage or Bacon?',
 'Skittles or M&Ms?',
 'Soup or Salad?',
 'Chicken or steak?',
 'Tacos or Burritos?',
 'Do you prefer the window or aisle seat on an airplane?',
 'TikTok or Instagram?',
 'Do you prefer to work remotely or in office?',
 'What comes first, milk or cereal?',
 'Do to typically go to bed before or after 11pm?',
 'How should toilet paper be rolled?',
 'Have you eaten lunch today?',
 'Headphones or Earbuds?',
 'If you had to go to sleep at the same time every night, would it be ...',
 'Is a hot dog a sandwich?',
 'Is a tomato a fruit or a vegetable?',
 'Is Apple better than Android?',
 'Is Tuesday or Wednesday better?',
 'Is your birth date odd or even?',
 'Is your birth MONTH even or odd?',
 'Is your birthday in the first fifteen days of the month?',
 'Matcha or Coffee?',
 'Hoodie + Shorts or Shirt + Pants?',
 'Noodles or Rice?',
 'Savory or sweet breakfast?',
 'Was Illinois Your Dream School?',
 'Sights and Sounds: Were you Orange or Blue?',
 'Seals or Penguins?',
 'Orange or Blue?',
 'Soda or Juice?',
 'North Pole or South Pole?',
 'Prefer Lecture of Lab in DISCOVERY?',
 'Computer Science or Statistics?',
 'Do you prefer Mom or Dad?',
 'Would you rather be Courageous Pizza or Honest Broccoli?',
 'Would you rather be too hot or too cold?',
 'When do you go to the gym?',
 'Orange or Apple?',
 "Would you rather know how you die or know when you'd die?",
 'Which of the following descriptions best matches your favorite movie?',
 'Is math red or blue?',
 'Do you get closer to 6 or 7 hours of sleep?',
 'How many classes are you taking this semester?',
 'How many credit hours are you taking?',
 'How many hours do you sleep in a night?',
 'How many siblings do you have?',
 'Pick a number between 1 and 10.',
 'What is your shoe size (US size)?',
 'How many cups (8 oz.) of water do you drink a day?',
 'What number do you consider as an unlucky number?',
 'How many people is the ideal number of people at a party?',
 'What is your phone battery percentage currently at?',
 'Besides the US, what country would you like to live in?',
 'What is your favorite color?',
 'Favorite way to spend your free time?',
 'What genre of music do you like the most?',
 'If you were an animal, which would you be? / What is your spirit animal?',
 'What do you think is the hardest major at UIUC?',
 'Who is your favorite music artist?',
 "What's your favorite social media app?",
 'What is your favorite game to play (either video game or IRL)?',
 'Where is your dream vacation spot?']

### Puzzle 1.3: Choosing Your Columns
From the above list of **columns** (questions), choose **at least 12 questions** to work with moving forward. Please use **only questions with binary answers** for this part of the analysis :) 

***Make sure to choose the questions intentionally! You'll want to pick questions you find interesting and questions that you think would best measure the similarity between 2 people (don't just pick the first 12 questions).***

These will be the questions used to **calculate your similarity** to other people in DISCOVERY! Feel free to include more if you'd like. 

Store them as a **list** of **strings** named `questions` in the Python cell below:

In [113]:
questions = ["Cookies or Brownies?",""
  'Do you prefer cats or dogs?',
  'Do you prefer Italian or Mexican food?',
  'Cookies or Brownies?',
  'Do you like apples or bananas?',
  'Waffles or pancakes?',
  'Night Owl or Early Bird?',
  'Do you typically shower in the morning or at night?',
  'Do you prefer sweet or savory food?',
  'Orange or Apple?',
  'Is math red or blue?',
  'Seals or Penguins?'
]
questions

['Cookies or Brownies?',
 'Do you prefer cats or dogs?',
 'Do you prefer Italian or Mexican food?',
 'Cookies or Brownies?',
 'Do you like apples or bananas?',
 'Waffles or pancakes?',
 'Night Owl or Early Bird?',
 'Do you typically shower in the morning or at night?',
 'Do you prefer sweet or savory food?',
 'Orange or Apple?',
 'Is math red or blue?',
 'Seals or Penguins?']

### 🔬 Test Case Checkpoint 🔬

In [114]:
## == PUZZLE 1.3 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('questions' in vars()), "Please name your list of questions `questions`."
assert(type(questions) == list and type(questions[0]) == str), "Make sure your `questions` variable is a list of strings."
assert(len(questions) >= 12), "Do you have at least 12 questions in your columns list?"
for q in questions:
   assert(q in df), f"\"{q}\" not in columns of `df`. Double check that you've copied each question correctly. The question texts should match up EXACTLY with the output from `df.columns.to_list()`."
for q in questions:
   assert(len(df[q].value_counts()) == 2), "Make sure that you've only included questions with binary answers in your columns list."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 2: The Similarity Function

Now that we have chosen the **questions** we'd like to evaluate, it's time to create a **function** to calculate a similarity value for each person, or each row in `df`.

In lecture, you learned that a Python **function** takes an **input** in and **returns** a **value**. 

For this specific function, we will take a **row** and calculate a **similarity score** for that row.

But first, **print your list of questions** using the Python cell below for reference:

In [115]:
questions

['Cookies or Brownies?',
 'Do you prefer cats or dogs?',
 'Do you prefer Italian or Mexican food?',
 'Cookies or Brownies?',
 'Do you like apples or bananas?',
 'Waffles or pancakes?',
 'Night Owl or Early Bird?',
 'Do you typically shower in the morning or at night?',
 'Do you prefer sweet or savory food?',
 'Orange or Apple?',
 'Is math red or blue?',
 'Seals or Penguins?']

### Puzzle 2.1: The Similarity Function

In the code below, you will find an outline for a `similarity` function that returns a similarity score:

> ```py
> def similarity(row):
>     # This function will keep track of a `score` of how similar two rows are with each other.
>     # The score begins at zero and we will add to it every time a row matches.
>     score = 0 
> 
>     # This if statement below checks to see if the `row` shares your choice between Coffee and Tea
>     # - If the values are the same (==), we add one to the score.
>     # - If the values are NOT the same, the `score = score + 1` line is skipped.
>     if row["Coffee or Tea?"] == my_row["Coffee or Tea?"]:
>         score = score + 1
>
>     # Finally, return the `score`.
>     # ...this line (the return statement) should always be the LAST line. 
>     return score
> ```

Using this same function structure, complete your `similarity` function below **using the questions you picked out earlier**.  This will require you to write **one if statement** for each question you selected:

In [116]:
def similarity(row):
    score = 0
    if row['Cookies or Brownies?'] == my_row['Cookies or Brownies?']:
        score=score + 1
    if row ['Do you prefer cats or dogs?'] == my_row['Do you prefer cats or dogs?']:
        score=score + 1
    if row ['Do you prefer Italian or Mexican food?'] == my_row['Do you prefer Italian or Mexican food?']:
        score=score + 1
    if row ['Cookies or Brownies?'] == my_row['Cookies or Brownies?']:
        score=score + 1
    if row ['Do you like apples or bananas?'] == my_row['Do you like apples or bananas?']:
        score=score + 1
    if row ['Waffles or pancakes?'] == my_row['Waffles or pancakes?']:
        score=score + 1
    if row ['Night Owl or Early Bird?'] == my_row['Night Owl or Early Bird?']:
        score=score + 1
    if row ['Do you typically shower in the morning or at night?'] == my_row['Do you typically shower in the morning or at night?']:
        score=score + 1
    if row ['Do you prefer sweet or savory food?'] == my_row['Do you prefer sweet or savory food?']:
        score=score + 1
    if row ['Orange or Apple?'] == my_row['Orange or Apple?']:
        score= score + 1
    if row ['Is math red or blue?'] == my_row['Is math red or blue?']:
        score=score + 1
    if row ['Seals or Penguins?'] == my_row ['Seals or Penguins?']:
        score=score + 1
    return score

### 🔬 Test Case Checkpoint 🔬

In [117]:
## == PUZZLE 2.1 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(similarity(my_row) == len(questions) or similarity(my_row) == my_row[questions].count()), "Ensure you've added all the questions from your list and ONLY questions from your list correctly to your similarity function."
assert( len(df.apply(similarity, axis = 1).unique()) > 2 ), "Your function must return differnet values for differnet rows."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 2.2: Applying the Similarity Function
Now that you've properly defined the similarity function, we need to **apply** it to the rest of the Hello Dataset DataFrame so we can produce a **similarity score** for each person who took the survey!

Using the above explanation as reference, **add a column** named `Similarity Score` to your original DataFrame that contains the value after running your similarity function you defined earlier across all rows:

(Hint): Look back to `lab_illini` part 2.2 & `lab_gpa` part 1.1

In [118]:
df["Similarity Score"] = df.apply(similarity, axis=1)
df

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
0,Prof. Wade,AL1,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Purple,Nerding Out,Pop EDM,Eagle,Physics,Taylor Swift,YouTube,Factorio,Mountain Cabin,5
1,Prof. Karle,AL1,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,pink,with people!!!,pop,sloth,computer science,Taylor Swift,instagram,cards,Maldives,7
2,Muhammad,Y20,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Green,Sleeping,Hip hop,Husky,Electrical Engineering,Kanye West,Instagram,Minecraft,Switzerland,10
3,Jake,Y10,Heads,Chocolate,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Yellow,Hang Out With Friends,Indie Music,Llama,Electrical Engineering,Tame Impala,Instagram,Volleyball,Switzerland Alps,3
4,Shourya,Y04,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Red,Youtube,Indie pop,Wolf,Astrophysics,Cigarettes after sex,Instagram,Spy,Iceland,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,arnav,Y31,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,Movies,...,Blue,Hang out with friends,R&b,Lion,Chemical engineering,NaN,Instagram,NaN,Indonesia,8
1196,Lorenzo,Y11,Heads,Chocolate,Morning,Even,Yes,Summer,In Gies College of Business,Movies,...,blue,sleep,jazz,dog,cs,MBY,wechat,MC,Canada,7
1197,CA Emma,Y20,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Green,Crocheting,Pop,Frog,Computer Science,Lady Gaga,TikTok,Minecraft,Italy,5
1198,CA Soph,Y01 Y14 Y15 Y18,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Red,Relaxing,Hyperpop,Rabbit,Aerospace Engineering,Ayesha Erotica,Pinterest,Twister,Mexico City,5
1199,Jay,Y07,Tails,Vanilla,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Blue,On Tiktok,R&B,Wolf,Chem E,Mac Demarco,TikTok,Basketball,Hawaii,7

### 🔬 Test Case Checkpoint 🔬

In [119]:
## == PUZZLE 2.2 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('Similarity Score' in df), "Make sure you've named and added the Similarity Score column to your original df."
assert(df['Similarity Score'].dtype == 'int64'), "Double check that you've called the similarity function correctly in your df.apply()."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 3: Finding your Twin(s)

Your last column `Similarity Score` in `df` is now a metric (a measurement) of how **similar** you are to everyone else in the class, based on the **questions you've chosen**!

Finally, we can do analytical Data Science!

### Puzzle 3.1: Your Twin in 107

Using the Python cell below, find the **person most similar to you in the entire course**. Think about how you would do this using the `Similarity Score` column.

Note that **you should be most similar to yourself** (you will always match yourself)! This is not the right answer. Find the person with the highest score ***aside from yourself***. *(There is a chance there can be multiple people tied as the person most similar to you and that's okay!)*

Make sure to display the rows.

In [120]:
df.nlargest(2,"Similarity Score")

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
798,Michelle,Y01,Heads,Vanilla,Night,Odd,Yes,Summer,Not in Gies,Movies,...,pink,Baking,Alternative Indie,cat,engineering,Black Party,tiktok,Sims,Grecce,12
77,Hannah,Y19,Heads,Vanilla,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,blue,Working out,country,leopard,Engineering,SZA,TikTok,basketball,Italy,11

### Puzzle 3.2: Your Lab Twin

Now, chances are your twin isn't in your lab section. Because we conveniently have our row, `Similarity Score` applied to the **entire** set of responses to the survey, we can create smaller DataFrames to answer more questions. 

We want to find the person most similar to you in **your lab section**, otherwise known as your lab twin! We can create a new DataFrame to answer this question. 

However, some of your CAs and TAs, who are part of your lab section, are in more than one lab section! Those who have multiple sections have `Y##, Y##...` in their Sections column. How can we create a DataFrame that includes the CAs and TAs who are in more than one lab section? Python saves the day again.

#### **The `contains` Function**
In Python, the `contains` function can be used to check if a specific **substring** is present in a **string**. 

This will come in handy for us, because we can see if `Y##` is in the **names** of any rows in our DataFrame.

Using the `contains` function, create a **new DataFrame** with everyone in your lab section: `df_section`. Part of the statement has been completed for you to show you how to use `contains`. Complete it and make sure to display the dataframe.

*Note that we have to cast our `Lab` column of `df` to a **string** by using `.str`.

*Second note: the `na=False` parameter in the `contains` function makes it so that we ignore the rows with no lab section.

In [121]:
df_section = df[(df['Lab'].str.contains("Y01",na=False))]
df_section

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
39,Antonio,Y01,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,Movies,...,Red,Video games,R&B,Honeybadger,Physics,The Weeknd,Twitter/X,Terraria,Switzerland,7
106,Dori,Y01,Heads,Chocolate,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,Red,Reading,Rap,bengal tiger,aerospace engineering,Joji,Instagram,Sims,wyoming,4
141,Praise,Y01,Heads,Vanilla,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,Grey,Watching shows,Christian,Raccoon,ECE,dont have one,YouTube,One word story,Korea,5
178,Lili,Y01,Heads,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,pastel pink,spend time with friends,R&B,bunny,ECE,NIKI,instagram,video game,Philippines,5
253,Tuan,Y01,Heads,Chocolate,Night,Even,No,Winter,Not in Gies,Movies,...,green,hanging out with friends,pop,cat,Engineering,Jvke,youtube,Valorant,japan,5
283,Chris,Y01,Tails,Vanilla,Morning,Even,No,Winter,Not in Gies,TV Shows,...,Purple,With friends,Kpop,Penguin,MechE,Twice,TikTok,Lego Star Wars III,Japan,7
294,Elias,Y01,Tails,Chocolate,Night,Odd,Yes,Winter,Not in Gies,Movies,...,blue,Listening to music,R&B,Fox,CS,T Swift,the red note,honor of kings,New Zealand,4
313,De'Asia,Y01,Heads,Chocolate,Morning,Odd,No,Summer,Not in Gies,TV Shows,...,orange,TikTok,Hip hop,Lion,Physics,Weeknd,TikTok,Sims,nothing,4
417,Gabi,Y01,Heads,Vanilla,Morning,Odd,Yes,Summer,In Gies College of Business,Movies,...,Cream,With friends,Country,Turtle,Como Sci,Zach Bryan,Tiktok,Monopoly,Greece,8
503,Eleanor,Y01,Heads,Vanilla,Morning,Odd,No,Summer,Not in Gies,Movies,...,Yellow,Outside,Pop rock,Rabbit,Computer Engineering,Prefab Sprout,TikTok,Cards,SGI Florida,7
544,Inseo,Y01,Heads,Chocolate,Morning,Odd,No,Winter,Not in Gies,TV Shows,...,green,watch youtube,pop,dog,mechanical engineering,the weekend,instagram,pikmin,horseshoe bend,2
608,Tingyu,Y01,NaN,Vanilla,Morning,Even,Yes,Summer,Not in Gies,Movies,...,red,golf,jazz,Dragon,Econ,Asen,wechat,valorant,sanya,6
623,Valeria,Y01,Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,TV Shows,...,Red,Watching Netflix,R&B,Monkey,Chemical Engineering,Frank Ocean,TikTok,Spongebob Krusty Cook Off,Brazil,6
727,Julia,Y01,Heads,Chocolate,Morning,Even,Yes,Winter,Not in Gies,Movies,...,Pink,Go on a run,Indie,Dolphin,Computer Science,Malcolm Todd,Instagram,Pickle Ball,Switzerland,5
747,Shivani,Y01,Heads,Vanilla,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Lilac,Hanging out on quad.,pop,Butterfly,Biochem,post malone,Instagram,Golf,Santorini,7
753,Jasmitha,Y01,Heads,Chocolate,Night,Even,No,Summer,In Gies College of Business,Movies,...,Pink,Sleep,Popular songs,Panda,Computer engineering,Weeknd,Instagram,Badminton,Italy,5
798,Michelle,Y01,Heads,Vanilla,Night,Odd,Yes,Summer,Not in Gies,Movies,...,pink,Baking,Alternative Indie,cat,engineering,Black Party,tiktok,Sims,Grecce,12
803,TA Jake,Y01 Y07,Tails,Vanilla,Morning,Odd,Yes,Summer,Not in Gies,TV Shows,...,Orange,Reading books,bluegrass/folk,Dog,ECE,Tyler Childers,tiktok,counter strike,Italy,7
814,Jissel,Y01,Heads,Chocolate,Morning,Odd,Yes,Winter,Not in Gies,Movies,...,pink,reading,rap,wolf,engineering,drake,tiktok,mortal combat,italy,7
974,Beata,Y01,Heads,Vanilla,Night,Odd,Yes,Summer,Not in Gies,TV Shows,...,Blue,Watching tv,House music,Jaguar,Architecture,Dom dolla,Facebook,Pokémon go,Bora bora,7
980,Honghan,Y01,Heads,Chocolate,Morning,Even,Yes,Summer,In Gies College of Business,Movies,...,blue,badminton or video games,R&B,Wolf,CS,Fang Datong,tiktok,Delta Force,south asia,5
992,CA Jai,Y01,Heads,Chocolate,Night,Odd,Yes,Summer,Not in Gies,Movies,...,Blue,Doing the Hello Survey,EDM,Orca,Computer Engineering,Ed Sheeran,Reddit,Catan,Indonesia,4
993,CA Mia,Y01,Tails,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,Purple,Getting coffee and going on a walk,Pop,Penguin,CS + Physics,Olivia Rodrigo,Instagram,Taboo,Japan,3
994,CA Jessica,Y01,Heads,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,Sage green,Reading,Indie pop,Llama,Physics,Noah Kahan,tiktok,Red (card game),Machu Picchu,7
998,Savanna,Y01,Heads,Vanilla,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,pink,hangout with friends,R&B,Penguin,Nursing,Beyonce,tik tok,Fortnight,Jamaica,5
1014,Sabrina,Y01,Heads,Vanilla,Night,Even,No,Winter,Not in Gies,Movies,...,Orange,With friends,Pop,Dog,Computer Science,The Weeknd,Tiktok,Pickleball,Thailand,5
1019,Ansh,Y01,Heads,Chocolate,Night,Odd,Yes,Summer,Not in Gies,TV Shows,...,purple,read,r&b,dog,engineering,drake,instagram,nba 2k,iceland,5
1023,Meer,Y01,Heads,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,Blue,Sleeping,Rap,Dolphin,Physics,Drake,Tiktok,Madden,Bali,7
1041,CA Talia,Y01,Heads,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Red,Reading or going on walks,Rock,Owl,Mathematics,Fleetwood Mac,Reddit,Star Wars Battlefront II,Prince Edward Island,7
1058,CA Eliana,Y01,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,Movies,...,Blue,Reading,Po,Sea otter,Computer Engineering,Itzhak Perlman,Goodreads,Pokemon,Vietnam,8
1059,Angela,Y01,Tails,Vanilla,Night,Odd,Yes,Summer,Not in Gies,TV Shows,...,Green,Using social media,Indie,cat,Actuarial Science,Gracie Abrams,Instagram,Minecraft,Seattle,7
1124,CA Maddy,Y01,Heads,Chocolate,Morning,Odd,No,Summer,In Gies College of Business,Movies,...,pink,working out,pop,cat,chemical engineering,taylor swift,tiktok,tennis,greece,8
1162,Talib,Y01,Heads,Chocolate,Night,Even,No,Winter,Not in Gies,TV Shows,...,blue,Play videogames,Hip hop,Pigeon,Physics,Adelle,Tiktok,Minecraft,machu picchu,4
1198,CA Soph,Y01 Y14 Y15 Y18,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Red,Relaxing,Hyperpop,Rabbit,Aerospace Engineering,Ayesha Erotica,Pinterest,Twister,Mexico City,5

### Puzzle 3.3: Your Lab Twin!

Similarly to Puzzle 3.1, find your lab section twin. Make sure to display the dataframe.

In [125]:
df_section.nlargest(2, "Similarity Score")

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
798,Michelle,Y01,Heads,Vanilla,Night,Odd,Yes,Summer,Not in Gies,Movies,...,pink,Baking,Alternative Indie,cat,engineering,Black Party,tiktok,Sims,Grecce,12
417,Gabi,Y01,Heads,Vanilla,Morning,Odd,Yes,Summer,In Gies College of Business,Movies,...,Cream,With friends,Country,Turtle,Como Sci,Zach Bryan,Tiktok,Monopoly,Greece,8

#### **➡️ Once you have that person, follow your TAs directions!<br> ➡️ They will tell you when to complete the rest of Puzzle 3.3**<br>

Help them get up to this point in the lab and let them find their DISCOVERY twin!  *(Are you twins of each other?)* 

➡️ Once you are **BOTH** to this section, introduce yourself and your DISCOVERY lab section "twin" to your lab TA. <br>
➡️ Make sure you know what your "Similarity Score" to your twin is! <br>
➡️ If you do this introduction to your TA **in-person during your lab section, you will earn +1 EC**! :)

Note that there may be ties in `Similarity Score` due to the usage of only parts of the dataset. If you're curious, you can go back and **add more questions** to your `questions` list and `similarity(row)` function, rerunning the code to have more evaluative similarity scores.

### Puzzle 3.4: The Course Staff
A lot of wonderful course staff work together to bring you all the content for Data Science DISCOVERY. 

The course staff of 107 consists of the **Professors, TAs, and CAs**. As you saw in the previous parts, they've all completed the Hello Survey too! 

Their response under the `Name` column is standardized and follows these formats:
- `Prof. [Name]`,
- `TA [Name]`, or
- `CA [Name]`

The `contains` function will come in handy for us once again, because we can see if `"CA "`, `"TA "`, or `"Prof. "` is in the **names** of any rows in our DataFrame.

Using the `contains` function, create a **new DataFrame** with just the course staff: `df_staff`, and display the dataframe. 

Read the following guide on **using `contains` to select all rows based on String contents**: https://discovery.cs.illinois.edu/guides/DataFrame-Row-Selection/dataframe-string-contains/

*Note that we have to cast our `Name` column of `df` to a **string** by using `.str`.

In [129]:
# IMPORTANT: Make sure you include a whitespace in 'CA ' and 'TA ' so that people with those
# #          letters in their name aren't included.  Whitespace matters! :)
df_staff= df[(df['Name'].str.contains("CA",na=False))|(df['Name'].str.contains("TA",na=False))|(df['Name'].str.contains("Prof",na=False))]
df_staff

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
0,Prof. Wade,AL1,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Purple,Nerding Out,Pop EDM,Eagle,Physics,Taylor Swift,YouTube,Factorio,Mountain Cabin,5
1,Prof. Karle,AL1,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,pink,with people!!!,pop,sloth,computer science,Taylor Swift,instagram,cards,Maldives,7
120,TA Tyler,"Y06, Y10",Tails,Chocolate,Night,Even,No,Winter,Not in Gies,TV Shows,...,Orange,Playing Terraria,Pop rock,Tardigrade,Chemical Engineering,Billy Joel,Reddit,Terraria,NaN,3
220,CA Lyndsey,"Y06, Y25",Heads,Chocolate,Night,Odd,Yes,Summer,Not in Gies,Movies,...,Red,With my dogs,Pop,Deer,Computer engineering,Gracie Abrams,Instagram,Jackbox,Italy,5
269,CA Ona,"Y20, Y23",Heads,Vanilla,Morning,Odd,No,Summer,Not in Gies,TV Shows,...,Blue,TikTok,Rock,Cat,Engineering,Hozier,TikTok,Clue,Iceland,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,TA Jackson,Y29 Y36,Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,TV Shows,...,Red,Research,Metal,Penguin,Art,Les Claypool,Reddit,Sea of Thieves,Italy,5
1164,CA Jaythan,"Y11, Y26",Heads,Vanilla,Night,Odd,Yes,Winter,In Gies College of Business,Movies,...,Black,Hanging with Friends,Mexican Regional,Penguin,Bioengineering,Peso Pluma,Instagram,Marvel Rivals,Paris,5
1176,CA Lara,"Y24, Y33, Y40",Heads,Chocolate,Night,Even,No,Winter,Not in Gies,Movies,...,Light teal,Reading,Shoegaze,Mayfly,Physics,Marina,Reddit,Minds Beneath Us,Japan,4
1197,CA Emma,Y20,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Green,Crocheting,Pop,Frog,Computer Science,Lady Gaga,TikTok,Minecraft,Italy,5
1198,CA Soph,Y01 Y14 Y15 Y18,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Red,Relaxing,Hyperpop,Rabbit,Aerospace Engineering,Ayesha Erotica,Pinterest,Twister,Mexico City,5

### 🔬 Test Case Checkpoint 🔬

In [130]:
## == PUZZLE 3.3 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('df_staff' in vars()), "Your DataFrame of course staff should be named 'df_staff'."
assert(len(df_staff) == 67), "Check you've added all the course staff correctly."
assert(len(df_staff.columns.to_list()) == 161), "You should have all of the questions columns and the Similarity Score column in df_staff." 

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 3.5: Course Staff Twin!

Now that we have the course staff responses in `df_staff`, find your course staff twin (the staff member who has the **highest Similarity Score** to you) and display it.

In [131]:
df_staff.nlargest(2, "Similarity Score")

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
458,CA Sarah,"Y34, Y41",Tails,Vanilla,Night,Even,No,Winter,Not in Gies,TV Shows,...,Blue,Drawing,Indie Pop,Cat,Computer Science,Stray Kids,Instagram,Omori,Japan,9
695,CA Renee,"Y38, Y43",Tails,Vanilla,Night,Even,No,Winter,In Gies College of Business,TV Shows,...,pink,Sleep,Indie rock,Cat,Physics,Good Kid,Red Note,Hades,Italy,9

### Analysis: Final Reflection

**Question 1:** Is it possible that the person that you found as your STAT107 "twin" may not find you as their twin? Explain your answer.

**Question 2:** Do you think the method we used to find similar people is effective? Explain why or why not and give at least one suggestion to improve it.

1. It is possible that the person I found my “twin” is not their “twin.” This is true because similarity is not mutual it all depends on how the “Similarity Score” is computed and who is compared. When I search for my twin, the software compares my data with all the rest, and finds the best match for me to somebody else. But that same person may have a higher similarity score with somebody else than with me when making the same comparison. The pairing therefore is not necessarily mutual, unless both have an identical similarity score pattern with respect to each other.
2. I think the method we used to find similar people was somewhat effective but could definitely be improved. The approach helped us identify people with similar data by comparing their “Similarity Scores,” but it only focused on specific variables that were included in the dataset. This means it doesn’t always capture other important factors like interests, background, or personality that might make two people truly similar. To improve the method, I would suggest adding more columns to the comparison, such as GPA, major, or survey responses, and making sure the data is normalized so one variable doesn’t overly influence the score. Another improvement could be finding mutual matches, where both people identify each other as their closest twin.

<hr style="color: #DD3403;">

# Submission

You're almost done!  All you need to do is to commit your lab to GitHub:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the Canvas instructions to commit this lab to your Git repository!

3. Your TA will grade your submission and provide you feedback after the lab is due. :)